services:
  - type: web
    name: march-cleaning
    env: node
    plan: free
    buildCommand: cd cleaning-services-website && npm install && npm run build
    startCommand: cd cleaning-services-website && npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
