// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// The @prisma/config package might not be available or necessary for all setups.
// For basic Next.js usage, Prisma typically reads from the schema and env directly.
// If this file was generated by a specific experimental feature, we'll revert to standard.

export default {
  schema: "prisma/schema.prisma",
};
