/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#4cd6fb",
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#001b3d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#405f91",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#43474f",
        "on-secondary": "#ffffff",
        "secondary-container": "#50d9fe",
        "on-tertiary-fixed": "#191c1e",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "primary": "#001736",
        "surface-container-low": "#eff4ff",
        "error": "#ba1a1a",
        "tertiary": "#141819",
        "on-tertiary-container": "#909395",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#004e5f",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-container": "#002b5b",
        "tertiary-container": "#292c2e",
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-variant": "#d3e4fe",
        "outline": "#747780",
        "on-primary": "#ffffff",
        "on-secondary-container": "#005c70",
        "on-primary-container": "#7594ca",
        "tertiary-fixed": "#e0e3e5",
        "on-primary-fixed-variant": "#264778",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#001f27",
        "inverse-primary": "#a9c7ff",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#b3ebff",
        "background": "#f8f9ff",
        "secondary": "#00677d",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#c4c6d0"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "section-gap": "80px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "compliance-note": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "sans": ['Outfit', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
